{% set name = "psyplot" %}
{% set version = "1.5.0" %}
{% set sha256 = "1f4ac3917d8061db2a3400f9b9e63728c79fcd532694227f4b70babb454adee8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps -vvv
  entry_points:
    - psyplot = psyplot.__main__:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - versioneer
    - tomli
  run:
    - python
    - matplotlib-base
    - funcargparse
    - docrep >=0.3
    - xarray >=0.17
    - pyyaml

test:
  commands:
    - psyplot --help
  imports:
    - psyplot
    - psyplot.config
    - psyplot.sphinxext
    - psyplot.data
    - psyplot.project

about:
  home: https://codebase.helmholtz.cloud/psyplot/psyplot
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - LICENSES/
  summary: Python package for interactive data visualization

  description: |
    psyplot is an cross-platform open source python project that mainly
    combines the plotting utilities of matplotlib and the data management of
    the xarray package and integrates them into a software that can be used via
    command-line and via a GUI.
  doc_url: https://psyplot.github.io
  dev_url: https://codebase.helmholtz.cloud/psyplot/psyplot

extra:
  recipe-maintainers:
    - valeriupredoi
    - Chilipp
